
-- movies
insert into movies (name, year, rating, count) values ('Побег из Шоушенка', 1994, 9.1, 5);
insert into movies (name, year, rating, count) values ('Тейлор Свифт: The Eras Tour ', 2023, 8.9, 41);
insert into movies (name, year, rating, count) values ('Человек-Паук: Паутина Вселенных', 2022, 8.9, 7);
insert into movies (name, year, rating, count) values ('Зеленая миля', 1999, 8.8, 13);
insert into movies (name, year, rating, count) values ('Крестный отец', 1972, 8.8, 27);
insert into movies (name, year, rating, count) values ('Начало', 2010, 8.8, 42);
insert into movies (name, year, rating, count) values ('Оппенгеймер', 2023, 8.7, 41);
insert into movies (name, year, rating, count) values ('Властелин Колец: Братство Кольца', 2001, 8.7, 49);
insert into movies (name, year, rating, count) values ('Форрест Гамп', 1994, 8.7, 5);
insert into movies (name, year, rating, count) values ('1+1', 2011, 8.7, 47);
insert into movies (name, year, rating, count) values ('Король Лев', 1994, 8.7, 15);
insert into movies (name, year, rating, count) values ('Терминатор 2: судный день', 1991, 8.7, 35);
insert into movies (name, year, rating, count) values ('Властелин Колец: Две крепости', 2002, 8.7, 34);
insert into movies (name, year, rating, count) values ('Криминальное чтиво', 1994, 8.7, 29);
insert into movies (name, year, rating, count) values ('BTS: Yet to Come in Cinemas', 2023, 8.7, 27);
insert into movies (name, year, rating, count) values ('Матрица', 1999, 8.7, 49);
insert into movies (name, year, rating, count) values ('Унесенные призраками', 2001, 8.6, 45);
insert into movies (name, year, rating, count) values ('Темный рыцарь', 2008, 8.6, 39);
insert into movies (name, year, rating, count) values ('Властелин Колец: Возвращение Короля', 2003, 8.6, 39);
insert into movies (name, year, rating, count) values ('Ну, погоди!', 1969, 8.6, 41);
insert into movies (name, year, rating, count) values ('Бойцовский клуб', 1999, 8.6, 32);
insert into movies (name, year, rating, count) values ('Назад в будущее', 1985, 8.6, 15);
insert into movies (name, year, rating, count) values ('Человек-паук: Нет пути домой', 2021, 8.6, 14);
insert into movies (name, year, rating, count) values ('Список Шиндлера', 1993, 8.6, 40);
insert into movies (name, year, rating, count) values ('Леон', 1994, 8.6, 5);
insert into movies (name, year, rating, count) values ('Стражи Галактики. Часть 3', 2023, 8.6, 16);
insert into movies (name, year, rating, count) values ('Ходячий замок', 2004, 8.6, 7);
insert into movies (name, year, rating, count) values ('Крестный отец 2', 1974, 8.5, 14);
insert into movies (name, year, rating, count) values ('Гладиатор', 2000, 8.5, 38);
insert into movies (name, year, rating, count) values ('Молчание ягнят', 1991, 8.5, 18);
insert into movies (name, year, rating, count) values ('Тайна Коко', 2017, 8.5, 41);
insert into movies (name, year, rating, count) values ('Хатико: самый верный друг', 2009, 8.5, 1);
insert into movies (name, year, rating, count) values ('Джентльмены удачи', 1971, 8.5, 39);
insert into movies (name, year, rating, count) values ('Твое имя', 2016, 8.5, 32);
insert into movies (name, year, rating, count) values ('Мстители: Война бесконечности', 2018, 8.5, 5);
insert into movies (name, year, rating, count) values ('Кот в сапогах 2: Последнее желание', 2022, 8.5, 46);
insert into movies (name, year, rating, count) values ('ВАЛЛ-И', 2008, 8.5, 44);
insert into movies (name, year, rating, count) values ('Пираты Карибского моря: Проклятие черной жемчужины', 2003, 8.5, 26);
insert into movies (name, year, rating, count) values ('Место встречи изменить нельзя', 1979, 8.5, 48);
insert into movies (name, year, rating, count) values ('FORD против FERRARI', 2019, 8.4, 17);
insert into movies (name, year, rating, count) values ('Храброе сердце', 1995, 8.4, 5);
insert into movies (name, year, rating, count) values ('Бриллиантовая рука', 1968, 8.4, 23);
insert into movies (name, year, rating, count) values ('Истребитель демонов: Поезд «Бесконечный»', 2020, 8.4, 39);
insert into movies (name, year, rating, count) values ('Мстители: Финал', 2019, 8.4, 30);
insert into movies (name, year, rating, count) values ('Интерстеллар', 2014, 8.4, 39);
insert into movies (name, year, rating, count) values ('Джанго освобожденный', 2012, 8.4, 8);
insert into movies (name, year, rating, count) values ('Зеленая книга', 2018, 8.4, 8);
insert into movies (name, year, rating, count) values ('Убийцы цветочной луны', 2023, 8.4, 37);
insert into movies (name, year, rating, count) values ('Семь', 1995, 8.4, 17);
insert into movies (name, year, rating, count) values ('Чужой', 1979, 8.4, 45);
insert into movies (name, year, rating, count) values ('Аватар', 2009, 8.4, 8);
insert into movies (name, year, rating, count) values ('Иван Васильевич меняет профессию', 1973, 8.4, 19);
insert into movies (name, year, rating, count) values ('Индиана Джонс: В поисках утраченного ковчега', 1981, 8.4, 29);
insert into movies (name, year, rating, count) values ('Бэтмен: начало', 2005, 8.4, 32);
insert into movies (name, year, rating, count) values ('Игры разума', 2001, 8.4, 41);
insert into movies (name, year, rating, count) values ('Изгой', 2000, 8.3, 44);
insert into movies (name, year, rating, count) values ('Престиж', 2006, 8.3, 34);
insert into movies (name, year, rating, count) values ('Мальчик и птица', 2023, 8.3, 32);
insert into movies (name, year, rating, count) values ('Поймай меня, если сможешь', 2002, 8.3, 38);
insert into movies (name, year, rating, count) values ('Отступники', 2006, 8.3, 23);
insert into movies (name, year, rating, count) values ('А зори здесь тихие', 1972, 8.3, 30);
insert into movies (name, year, rating, count) values ('Остров проклятых', 2009, 8.3, 9);
insert into movies (name, year, rating, count) values ('Чужие', 1986, 8.3, 37);
insert into movies (name, year, rating, count) values ('Титаник', 1997, 8.3, 28);
insert into movies (name, year, rating, count) values ('Крепкий орешек', 1988, 8.3, 37);
insert into movies (name, year, rating, count) values ('Отец', 2020, 8.3, 20);
insert into movies (name, year, rating, count) values ('Человек-паук: Через вселенные', 2018, 8.3, 14);
insert into movies (name, year, rating, count) values ('Аватар 2: Путь воды', 2022, 8.3, 42);
insert into movies (name, year, rating, count) values ('Судзумэ, закрывающая двери', 2022, 8.3, 29);
insert into movies (name, year, rating, count) values ('Топ Ган: Мэверик', 2022, 8.3, 19);
insert into movies (name, year, rating, count) values ('Миссия: невыполнима. Смертельная расплата. Часть 1', 2023, 8.3, 7);
insert into movies (name, year, rating, count) values ('Душа', 2020, 8.3, 1);
insert into movies (name, year, rating, count) values ('Как приручить дракона', 2010, 8.3, 46);
insert into movies (name, year, rating, count) values ('Приключения Шерлока Холмса и доктора Ватсона: Охота на тигра', 1980, 8.3, 2);
insert into movies (name, year, rating, count) values ('Капернаум', 2018, 8.3, 32);
insert into movies (name, year, rating, count) values ('Гарри Поттер и Дары смерти. Часть вторая', 2011, 8.3, 39);
insert into movies (name, year, rating, count) values ('Джон Уик 4', 2023, 8.3, 29);
insert into movies (name, year, rating, count) values ('Джокер', 2019, 8.3, 47);
insert into movies (name, year, rating, count) values ('Джентльмены', 2020, 8.3, 39);
insert into movies (name, year, rating, count) values ('Брат', 1997, 8.3, 38);
insert into movies (name, year, rating, count) values ('Переводчик', 2023, 8.3, 6);
insert into movies (name, year, rating, count) values ('12 стульев', 1976, 8.3, 19);
insert into movies (name, year, rating, count) values ('Вайолет Эвергарден. Фильм', 2020, 8.2, 5);
insert into movies (name, year, rating, count) values ('Любовь и голуби', 1984, 8.2, 4);
insert into movies (name, year, rating, count) values ('Вечное сияние чистого разума', 2004, 8.2, 44);
insert into movies (name, year, rating, count) values ('Лицо со шрамом', 1983, 8.2, 20);
insert into movies (name, year, rating, count) values ('По соображениям совести', 2016, 8.2, 22);
insert into movies (name, year, rating, count) values ('Богемская рапсодия', 2018, 8.2, 5);
insert into movies (name, year, rating, count) values ('Служебный роман', 1977, 8.2, 8);
insert into movies (name, year, rating, count) values ('День сурка', 1993, 8.2, 42);
insert into movies (name, year, rating, count) values ('Принцесса Мононоке', 1997, 8.2, 1);
insert into movies (name, year, rating, count) values ('Шрэк', 2001, 8.2, 12);
insert into movies (name, year, rating, count) values ('Корпорация Монстров', 2001, 8.2, 13);
insert into movies (name, year, rating, count) values ('Зверополис', 2016, 8.2, 16);
insert into movies (name, year, rating, count) values ('Спасти рядового Райана', 1998, 8.2, 3);
insert into movies (name, year, rating, count) values ('Реквием по мечте', 2000, 8.2, 24);
insert into movies (name, year, rating, count) values ('Схватка', 1995, 8.2, 10);



-- genres
insert into genres (name) values ('драма');
insert into genres (name) values ('триллер');
insert into genres (name) values ('музыка');
insert into genres (name) values ('боевик');
insert into genres (name) values ('приключения');
insert into genres (name) values ('анимация');
insert into genres (name) values ('фантастика');
insert into genres (name) values ('биография');
insert into genres (name) values ('исторический');
insert into genres (name) values ('фэнтези');
insert into genres (name) values ('комедия');
insert into genres (name) values ('мелодрама');
insert into genres (name) values ('мюзикл');
insert into genres (name) values ('семейный');
insert into genres (name) values ('аниме');
insert into genres (name) values ('мистика');
insert into genres (name) values ('короткометражный');
insert into genres (name) values ('военный');
insert into genres (name) values ('криминал');
insert into genres (name) values ('сказка');
insert into genres (name) values ('детектив');
insert into genres (name) values ('спорт');
insert into genres (name) values ('вестерн');
insert into genres (name) values ('ужасы');

-- movies_genres
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Побег из Шоушенка'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Побег из Шоушенка'), (select id from genres where name = 'триллер'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Тейлор Свифт: The Eras Tour '), (select id from genres where name = 'музыка'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Человек-Паук: Паутина Вселенных'), (select id from genres where name = 'боевик'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Человек-Паук: Паутина Вселенных'), (select id from genres where name = 'приключения'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Человек-Паук: Паутина Вселенных'), (select id from genres where name = 'анимация'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Зеленая миля'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Крестный отец'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Крестный отец'), (select id from genres where name = 'триллер'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Начало'), (select id from genres where name = 'боевик'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Начало'), (select id from genres where name = 'фантастика'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Начало'), (select id from genres where name = 'триллер'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Оппенгеймер'), (select id from genres where name = 'биография'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Оппенгеймер'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Оппенгеймер'), (select id from genres where name = 'исторический'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Властелин Колец: Братство Кольца'), (select id from genres where name = 'приключения'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Властелин Колец: Братство Кольца'), (select id from genres where name = 'боевик'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Властелин Колец: Братство Кольца'), (select id from genres where name = 'фэнтези'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Форрест Гамп'), (select id from genres where name = 'комедия'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Форрест Гамп'), (select id from genres where name = 'мелодрама'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Форрест Гамп'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = '1+1'), (select id from genres where name = 'комедия'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = '1+1'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = '1+1'), (select id from genres where name = 'биография'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Король Лев'), (select id from genres where name = 'мюзикл'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Король Лев'), (select id from genres where name = 'приключения'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Король Лев'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Король Лев'), (select id from genres where name = 'семейный'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Король Лев'), (select id from genres where name = 'комедия'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Король Лев'), (select id from genres where name = 'анимация'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Терминатор 2: судный день'), (select id from genres where name = 'боевик'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Терминатор 2: судный день'), (select id from genres where name = 'триллер'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Терминатор 2: судный день'), (select id from genres where name = 'фантастика'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Терминатор 2: судный день'), (select id from genres where name = 'приключения'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Властелин Колец: Две крепости'), (select id from genres where name = 'приключения'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Властелин Колец: Две крепости'), (select id from genres where name = 'фэнтези'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Властелин Колец: Две крепости'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Криминальное чтиво'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'BTS: Yet to Come in Cinemas'), (select id from genres where name = 'музыка'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Матрица'), (select id from genres where name = 'боевик'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Матрица'), (select id from genres where name = 'фантастика'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Матрица'), (select id from genres where name = 'триллер'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Унесенные призраками'), (select id from genres where name = 'аниме '));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Унесенные призраками'), (select id from genres where name = 'семейный'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Унесенные призраками'), (select id from genres where name = 'анимация'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Унесенные призраками'), (select id from genres where name = 'приключения'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Темный рыцарь'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Темный рыцарь'), (select id from genres where name = 'мистика'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Темный рыцарь'), (select id from genres where name = 'триллер'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Темный рыцарь'), (select id from genres where name = 'боевик'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Властелин Колец: Возвращение Короля'), (select id from genres where name = 'фэнтези'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Ну, погоди!'), (select id from genres where name = 'короткометражный'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Ну, погоди!'), (select id from genres where name = 'анимация'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Бойцовский клуб'), (select id from genres where name = 'триллер'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Бойцовский клуб'), (select id from genres where name = 'боевик'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Бойцовский клуб'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Назад в будущее'), (select id from genres where name = 'приключения'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Назад в будущее'), (select id from genres where name = 'фантастика'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Назад в будущее'), (select id from genres where name = 'комедия'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Назад в будущее'), (select id from genres where name = 'боевик'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Человек-паук: Нет пути домой'), (select id from genres where name = 'фантастика'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Человек-паук: Нет пути домой'), (select id from genres where name = 'боевик'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Человек-паук: Нет пути домой'), (select id from genres where name = 'приключения'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Список Шиндлера'), (select id from genres where name = 'исторический'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Список Шиндлера'), (select id from genres where name = 'военный'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Список Шиндлера'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Список Шиндлера'), (select id from genres where name = 'биография'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Леон'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Леон'), (select id from genres where name = 'триллер'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Леон'), (select id from genres where name = 'криминал'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Стражи Галактики. Часть 3'), (select id from genres where name = 'фантастика'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Стражи Галактики. Часть 3'), (select id from genres where name = 'боевик'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Стражи Галактики. Часть 3'), (select id from genres where name = 'приключения'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Ходячий замок'), (select id from genres where name = 'аниме '));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Ходячий замок'), (select id from genres where name = 'сказка'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Ходячий замок'), (select id from genres where name = 'фантастика'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Ходячий замок'), (select id from genres where name = 'мелодрама'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Крестный отец 2'), (select id from genres where name = 'триллер'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Крестный отец 2'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Гладиатор'), (select id from genres where name = 'приключения'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Гладиатор'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Гладиатор'), (select id from genres where name = 'боевик'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Молчание ягнят'), (select id from genres where name = 'триллер'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Молчание ягнят'), (select id from genres where name = 'криминал'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Тайна Коко'), (select id from genres where name = 'анимация'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Тайна Коко'), (select id from genres where name = 'приключения'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Хатико: самый верный друг'), (select id from genres where name = 'семейный'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Хатико: самый верный друг'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Джентльмены удачи'), (select id from genres where name = 'криминал'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Джентльмены удачи'), (select id from genres where name = 'комедия'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Твое имя'), (select id from genres where name = 'анимация'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Твое имя'), (select id from genres where name = 'фэнтези'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Твое имя'), (select id from genres where name = 'мелодрама'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Твое имя'), (select id from genres where name = 'аниме '));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Мстители: Война бесконечности'), (select id from genres where name = 'боевик'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Мстители: Война бесконечности'), (select id from genres where name = 'фантастика'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Кот в сапогах 2: Последнее желание'), (select id from genres where name = 'анимация'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Кот в сапогах 2: Последнее желание'), (select id from genres where name = 'комедия'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Кот в сапогах 2: Последнее желание'), (select id from genres where name = 'приключения'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'ВАЛЛ-И'), (select id from genres where name = 'семейный'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'ВАЛЛ-И'), (select id from genres where name = 'фэнтези'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'ВАЛЛ-И'), (select id from genres where name = 'анимация'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Пираты Карибского моря: Проклятие черной жемчужины'), (select id from genres where name = 'приключения'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Пираты Карибского моря: Проклятие черной жемчужины'), (select id from genres where name = 'боевик'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Пираты Карибского моря: Проклятие черной жемчужины'), (select id from genres where name = 'приключения'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Пираты Карибского моря: Проклятие черной жемчужины'), (select id from genres where name = 'боевик'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Место встречи изменить нельзя'), (select id from genres where name = 'криминал'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Место встречи изменить нельзя'), (select id from genres where name = 'детектив'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Место встречи изменить нельзя'), (select id from genres where name = 'боевик'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'FORD против FERRARI'), (select id from genres where name = 'биография'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'FORD против FERRARI'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'FORD против FERRARI'), (select id from genres where name = 'спорт'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Храброе сердце'), (select id from genres where name = 'военный'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Храброе сердце'), (select id from genres where name = 'биография'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Храброе сердце'), (select id from genres where name = 'боевик'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Храброе сердце'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Бриллиантовая рука'), (select id from genres where name = 'комедия'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Бриллиантовая рука'), (select id from genres where name = 'приключения'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Бриллиантовая рука'), (select id from genres where name = 'криминал'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Истребитель демонов: Поезд «Бесконечный»'), (select id from genres where name = 'боевик'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Истребитель демонов: Поезд «Бесконечный»'), (select id from genres where name = 'приключения'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Истребитель демонов: Поезд «Бесконечный»'), (select id from genres where name = 'анимация'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Мстители: Финал'), (select id from genres where name = 'боевик'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Мстители: Финал'), (select id from genres where name = 'фантастика'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Интерстеллар'), (select id from genres where name = 'фантастика'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Джанго освобожденный'), (select id from genres where name = 'вестерн'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Зеленая книга'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Убийцы цветочной луны'), (select id from genres where name = 'триллер'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Убийцы цветочной луны'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Убийцы цветочной луны'), (select id from genres where name = 'криминал'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Убийцы цветочной луны'), (select id from genres where name = 'детектив'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Убийцы цветочной луны'), (select id from genres where name = 'вестерн'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Убийцы цветочной луны'), (select id from genres where name = 'исторический'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Семь'), (select id from genres where name = 'мистика'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Семь'), (select id from genres where name = 'криминал'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Семь'), (select id from genres where name = 'триллер'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Чужой'), (select id from genres where name = 'ужасы'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Чужой'), (select id from genres where name = 'фантастика'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Чужой'), (select id from genres where name = 'триллер'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Аватар'), (select id from genres where name = 'боевик'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Аватар'), (select id from genres where name = 'фантастика'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Аватар'), (select id from genres where name = 'триллер'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Иван Васильевич меняет профессию'), (select id from genres where name = 'комедия'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Иван Васильевич меняет профессию'), (select id from genres where name = 'фантастика'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Индиана Джонс: В поисках утраченного ковчега'), (select id from genres where name = 'приключения'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Индиана Джонс: В поисках утраченного ковчега'), (select id from genres where name = 'триллер'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Индиана Джонс: В поисках утраченного ковчега'), (select id from genres where name = 'боевик'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Бэтмен: начало'), (select id from genres where name = 'криминал'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Бэтмен: начало'), (select id from genres where name = 'триллер'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Бэтмен: начало'), (select id from genres where name = 'приключения'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Бэтмен: начало'), (select id from genres where name = 'сказка'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Бэтмен: начало'), (select id from genres where name = 'боевик'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Игры разума'), (select id from genres where name = 'мистика'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Игры разума'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Игры разума'), (select id from genres where name = 'биография'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Изгой'), (select id from genres where name = 'приключения'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Изгой'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Престиж'), (select id from genres where name = 'сказка'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Престиж'), (select id from genres where name = 'триллер'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Престиж'), (select id from genres where name = 'фантастика'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Престиж'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Мальчик и птица'), (select id from genres where name = 'анимация'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Мальчик и птица'), (select id from genres where name = 'аниме '));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Поймай меня, если сможешь'), (select id from genres where name = 'комедия'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Отступники'), (select id from genres where name = 'криминал'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Отступники'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Отступники'), (select id from genres where name = 'триллер'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'А зори здесь тихие'), (select id from genres where name = 'исторический'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'А зори здесь тихие'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'А зори здесь тихие'), (select id from genres where name = 'военный'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Остров проклятых'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Остров проклятых'), (select id from genres where name = 'мистика'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Остров проклятых'), (select id from genres where name = 'триллер'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Чужие'), (select id from genres where name = 'триллер'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Чужие'), (select id from genres where name = 'ужасы'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Чужие'), (select id from genres where name = 'боевик'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Чужие'), (select id from genres where name = 'фантастика'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Титаник'), (select id from genres where name = 'мелодрама'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Титаник'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Титаник'), (select id from genres where name = 'приключения'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Крепкий орешек'), (select id from genres where name = 'триллер'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Крепкий орешек'), (select id from genres where name = 'криминал'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Крепкий орешек'), (select id from genres where name = 'боевик'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Отец'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Человек-паук: Через вселенные'), (select id from genres where name = 'анимация'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Человек-паук: Через вселенные'), (select id from genres where name = 'приключения'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Человек-паук: Через вселенные'), (select id from genres where name = 'фантастика'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Аватар 2: Путь воды'), (select id from genres where name = 'приключения'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Аватар 2: Путь воды'), (select id from genres where name = 'боевик'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Аватар 2: Путь воды'), (select id from genres where name = 'фантастика'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Судзумэ, закрывающая двери'), (select id from genres where name = 'аниме '));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Судзумэ, закрывающая двери'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Топ Ган: Мэверик'), (select id from genres where name = 'боевик'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Миссия: невыполнима. Смертельная расплата. Часть 1'), (select id from genres where name = 'боевик'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Миссия: невыполнима. Смертельная расплата. Часть 1'), (select id from genres where name = 'криминал'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Миссия: невыполнима. Смертельная расплата. Часть 1'), (select id from genres where name = 'триллер'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Душа'), (select id from genres where name = 'анимация'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Душа'), (select id from genres where name = 'семейный'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Душа'), (select id from genres where name = 'приключения'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Душа'), (select id from genres where name = 'комедия'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Как приручить дракона'), (select id from genres where name = 'анимация'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Как приручить дракона'), (select id from genres where name = 'семейный'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Как приручить дракона'), (select id from genres where name = 'сказка'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Приключения Шерлока Холмса и доктора Ватсона: Охота на тигра'), (select id from genres where name = 'криминал'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Приключения Шерлока Холмса и доктора Ватсона: Охота на тигра'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Приключения Шерлока Холмса и доктора Ватсона: Охота на тигра'), (select id from genres where name = 'мистика'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Капернаум'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Гарри Поттер и Дары смерти. Часть вторая'), (select id from genres where name = 'семейный'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Гарри Поттер и Дары смерти. Часть вторая'), (select id from genres where name = 'фэнтези'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Гарри Поттер и Дары смерти. Часть вторая'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Гарри Поттер и Дары смерти. Часть вторая'), (select id from genres where name = 'мистика'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Гарри Поттер и Дары смерти. Часть вторая'), (select id from genres where name = 'приключения'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Джон Уик 4'), (select id from genres where name = 'боевик'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Джон Уик 4'), (select id from genres where name = 'триллер'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Джон Уик 4'), (select id from genres where name = 'криминал'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Джокер'), (select id from genres where name = 'криминал'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Джокер'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Джентльмены'), (select id from genres where name = 'боевик'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Джентльмены'), (select id from genres where name = 'криминал'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Брат'), (select id from genres where name = 'боевик'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Брат'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Переводчик'), (select id from genres where name = 'боевик'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Переводчик'), (select id from genres where name = 'триллер'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Переводчик'), (select id from genres where name = 'криминал'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = '12 стульев'), (select id from genres where name = 'комедия'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = '12 стульев'), (select id from genres where name = 'детектив'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Вайолет Эвергарден. Фильм'), (select id from genres where name = 'анимация'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Вайолет Эвергарден. Фильм'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Вайолет Эвергарден. Фильм'), (select id from genres where name = 'фэнтези'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Любовь и голуби'), (select id from genres where name = 'комедия'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Любовь и голуби'), (select id from genres where name = 'мелодрама'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Вечное сияние чистого разума'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Вечное сияние чистого разума'), (select id from genres where name = 'комедия'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Вечное сияние чистого разума'), (select id from genres where name = 'мелодрама'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Лицо со шрамом'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Лицо со шрамом'), (select id from genres where name = 'криминал'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'По соображениям совести'), (select id from genres where name = 'военный'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'По соображениям совести'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'По соображениям совести'), (select id from genres where name = 'биография'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Богемская рапсодия'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Богемская рапсодия'), (select id from genres where name = 'биография'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Богемская рапсодия'), (select id from genres where name = 'мюзикл'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Служебный роман'), (select id from genres where name = 'мелодрама'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Служебный роман'), (select id from genres where name = 'комедия'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'День сурка'), (select id from genres where name = 'комедия'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'День сурка'), (select id from genres where name = 'мелодрама'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'День сурка'), (select id from genres where name = 'фантастика'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Принцесса Мононоке'), (select id from genres where name = 'аниме '));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Принцесса Мононоке'), (select id from genres where name = 'сказка'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Принцесса Мононоке'), (select id from genres where name = 'приключения'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Принцесса Мононоке'), (select id from genres where name = 'анимация'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Принцесса Мононоке'), (select id from genres where name = 'триллер'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Принцесса Мононоке'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Шрэк'), (select id from genres where name = 'анимация'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Шрэк'), (select id from genres where name = 'семейный'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Шрэк'), (select id from genres where name = 'комедия'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Корпорация Монстров'), (select id from genres where name = 'семейный'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Корпорация Монстров'), (select id from genres where name = 'сказка'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Корпорация Монстров'), (select id from genres where name = 'комедия'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Корпорация Монстров'), (select id from genres where name = 'анимация'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Зверополис'), (select id from genres where name = 'анимация'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Зверополис'), (select id from genres where name = 'боевик'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Зверополис'), (select id from genres where name = 'приключения'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Зверополис'), (select id from genres where name = 'семейный'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Зверополис'), (select id from genres where name = 'комедия'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Спасти рядового Райана'), (select id from genres where name = 'боевик'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Спасти рядового Райана'), (select id from genres where name = 'военный'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Спасти рядового Райана'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Реквием по мечте'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Реквием по мечте'), (select id from genres where name = 'криминал'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Схватка'), (select id from genres where name = 'драма'));
insert into movies_genres (movie_id, genre_id) values ((select id from movies where name = 'Схватка'), (select id from genres where name = 'криминал'));

